### ISSUE TITLE
BUG: My posts are not visible in threads

### ISSUE THREAD

**Issue by boreq** [planetary-social/viewer-frontend#89]
Link to my profile view:
https://planetary.link/@qFtLJ6P5Eh9vKxnj7Rsh8SkE6B6Z36DVLP7ZOKNeQ/Y=.ed25519

There are two threads visible in my profile view. In both cases it is unclear why they show up. My personal posts made in those threads are not rendered and my friends asked me why other people's posts show up in my profile view. I think we should either make sure that the profile owner's posts are clearly visible or hide threads like this.

![2022-02-22 14:21:06](https://user-images.githubusercontent.com/1935975/155140737-a31a877f-7719-4017-9ee7-a75a854b35c9.png)

**Comment by nichoth** [comment]
This is b/c we are paginating the replies in threads to only ~3 posts or something, but we are getting any thread in which the profile has replied.

* [ ] should not paginate the replies, should display all of them

**Comment by setch-l** [comment]
@nichoth - It sounds like from the comments that this was an issue of forked threads. How do I fork a thread to reproduce?

**Comment by nichoth** [comment]
@setch-l For the time being I've considered 'forked' messages to be out of scope of the initial product/iteration. 

Actually I'm not clear on what a 'forked' message means vs a reply message. It is a message with a key `{ fork }` in the json, vs a reply, that has a `{ root }` key. However I don't know what that signifies -- the difference between fork and reply. 

I did try looking through the ssb docs and I didn't see something.

Does anyone else -- @boreq, @rabble, @martindsq, @mplorentz, @Chardot -- have more info about it?

**Comment by setch-l** [comment]
Hi @nichoth - So did you fix anything for this or are you proposing to not fix anything?

**Comment by nichoth** [comment]
Sorry, I realized that it's not clear what is happening with this.

I did make a change -- https://github.com/planetary-social/planetary-pub/commit/6e904ed352fe2fa272bd3a834e5ffc66b33e78e6#diff-e85730e21e20c1fe28c6da049bdcae9b6942f68f54d718e26c88d4c322b01525 

although it looks like it was maybe a commit straight to main instead of a PR, so bad 
git etiquette on my part.

What I've done is now we are just *not showing* threads that the profile's author has forked.
